CREATE TABLE IF NOT EXISTS users (
   id TEXT NOT NULL,
   email TEXT UNIQUE NOT NULL,
   password BYTEA NOT NULL,
   max_todo INTEGER DEFAULT 5 NOT NULL,
   created_at TIMESTAMP NOT NULL,
   CONSTRAINT users_pk PRIMARY KEY (id)
);