package e

// GetMsg get error information based on Code
func GetMsg(code int) string {
	msg, ok := Msg[code]
	if ok {
		return msg
	}
	return Msg[ERROR]
}

var Msg = map[int]string{
	SUCCESS_BOOL: "OK",
	ERROR_BOOL:   "FAIL",

	SUCCESS: "success",
	ERR:     "error",

	SUCCESS_LOGIN:                  "success_login",
	SUCCESS_REGISTER:               "success_register",
	SUCCESS_UPDATE_PASSWORD:        "success_update_password",
	SUCCESS_UPDATE_SECOND_PASSWORD: "success_update_second_password",
	SUCCESS_UPDATE_PROFILE:         "success_update_profile",
	SUCCESS_UPDATE_BENEFICIARY:     "success_update_beneficiary",
	SUCCESS_UPDATE_AVATAR:          "success_update_avatar",

	SUCCESS_IN_CHECKING_PASSWORD:                    "Password is now available to update",
	SUCCESS_UPDATE_BANK:                             "success_update_bank_info",
	ERROR:                                           "Internal Server Error",
	ERROR_UNAUTHORIZES:                              "Unauthorized",
	INVALID_PARAMS:                                  "Request parameter error",
	ERROR_EXIST_TAG:                                 "已存在该标签名称",
	ERROR_EXIST_TAG_FAIL:                            "获取已存在标签失败",
	ERROR_NOT_EXIST_TAG:                             "该标签不存在",
	ERROR_GET_TAGS_FAIL:                             "获取所有标签失败",
	ERROR_COUNT_TAG_FAIL:                            "统计标签失败",
	ERROR_ADD_TAG_FAIL:                              "新增标签失败",
	ERROR_EDIT_TAG_FAIL:                             "修改标签失败",
	ERROR_DELETE_TAG_FAIL:                           "删除标签失败",
	ERROR_EXPORT_TAG_FAIL:                           "导出标签失败",
	ERROR_IMPORT_TAG_FAIL:                           "导入标签失败",
	ERROR_NOT_EXIST_ARTICLE:                         "该文章不存在",
	ERROR_ADD_ARTICLE_FAIL:                          "新增文章失败",
	ERROR_DELETE_ARTICLE_FAIL:                       "删除文章失败",
	ERROR_CHECK_EXIST_ARTICLE_FAIL:                  "检查文章是否存在失败",
	ERROR_EDIT_ARTICLE_FAIL:                         "修改文章失败",
	ERROR_COUNT_ARTICLE_FAIL:                        "统计文章失败",
	ERROR_GET_ARTICLES_FAIL:                         "获取多个文章失败",
	ERROR_GET_ARTICLE_FAIL:                          "Failed to get a single article",
	ERROR_GEN_ARTICLE_POSTER_FAIL:                   "生成文章海报失败",
	ERROR_AUTH_CHECK_TOKEN_FAIL:                     "Token鉴权失败",
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT:                  "Token已超时",
	ERROR_AUTH_TOKEN:                                "Token生成失败",
	ERROR_AUTH_CAPTCHA:                              "Captcha Invalid.",
	ERROR_AUTH:                                      "Invalid Username Or Password",
	ERROR_AUTH_PASSWORD:                             "Invalid Password",
	ERROR_UPLOAD_SAVE_IMAGE_FAIL:                    "保存图片失败",
	ERROR_UPLOAD_CHECK_IMAGE_FAIL:                   "检查图片失败",
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT:                 "校验图片错误，图片格式或大小有问题",
	ERROR_AUTH_SECONDARY_PASSWORD:                   "Invalid Secondary Password",
	ERROR_IN_REGISTER_MEMBER_PROCESS:                "Error Occur In Register Member Process",
	ERROR_IN_CHECK_PASSWORD_PROCESS:                 "Incorrect Secondary Password Or Password",
	ERROR_IN_CHECK_SEC_PASSWORD_PROCESS:             "Password And Secondary Password Cannot Be The Same",
	ERROR_IN_CHANGE_PASSWORD_PROCESS:                "Error Occur In Change Password Process",
	ERROR_IN_CHANGE_SEC_PASSWORD_PROCESS:            "Error Occur In Change Second Password Process",
	ERROR_IN_TRANSFER_PROCESS:                       "Error Occur In Wallet Transfer Process",
	ERROR_IN_TOPUP_MW_PROCESS:                       "Error Occur In Topup MW Process",
	ERROR_IN_GENERATE_SALES_ORDER:                   "Error Occur In Generate Sales Order Process",
	ERROR_DUPLICATE_USERNAME:                        "Username Already Taken",
	ERROR_GET_COUNTRIES:                             "Error Occur In Get Countries Process",
	ERROR_IN_GET_MEMBER:                             "Error Occur In Get Member Process",
	ERROR_IN_GET_WALLET:                             "Error Occur In Get Wallets Process",
	ERROR_IN_GET_PAYMENT_TYPE:                       "Error Occur In Get Payment Type",
	ERROR_IN_GET_PACKAGE:                            "Error Occur In Get Package",
	ERROR_WALLET_LOCK:                               "Your Current Ewallet Type Has Been Locked From Doing Transfer",
	ERROR_IN_CHECK_PAY_AMOUNT:                       "Please Pay Exact Amount",
	ERROR_IN_CHECK_PAY_AMOUNT_GREATER_THAN_MAX:      "Maximum Pay Amount Is %f",
	ERROR_IN_CHECK_PAY_AMOUNT_LOWER_THAN_MIN:        "Minimum Pay Amount Is %f",
	ERROR_IN_CHECK_WALLET_BALLANCE:                  "Error Occur In Check Wallet Balance",
	ERROR_IN_CHECK_TOPUP_AMOUNT_MIN:                 "Please Enter Amount Bigger Than 10",
	ERROR_IN_UPDATE_PROFILE_PROCESS:                 "Error Occur In Update Profile Process",
	ERROR_IN_GET_PIN:                                "Pin Not Exists",
	ERROR_PIN_CODE_USED:                             "Pin Code Used",
	ERROR_PIN_CODE_CANCELLED:                        "Pin Code Cancelled",
	ERROR_PIN_CHECK:                                 "Error In Pin Code Check Process",
	ERROR_IN_PURCHASE_PIN_PROCESS:                   "Error In Purchase Pin Process",
	ERROR_IN_PURCHASE_PIN_AGENT:                     "Agent Cannot Purchase PIN",
	ERROR_IN_PUBLIC_REGISTER_ERR_SPONSOR_CODE:       "Error Referral Code",
	ERROR_IN_REGISTER_ERR_SPONSOR_CODE:              "Please Enter The Correct Referral Code",
	ERROR_IN_REGISTER_ERR_UPLINE_CODE:               "Please Enter The Correct Upline Code",
	ERROR_IN_REGISTER_ERR_SPONSOR_NOT_DONWLINE:      "Referral Is Not One Of Your Miner",
	ERROR_IN_ACTIVATE_REQUIRED_REFERRAL_CODE:        "Please Enter Referral Code",
	ERROR_IN_ACTIVATE_REFERRAL_CODE_NOT_MEM:         "Referral Cannot Be An Inactive Member",
	ERROR_IN_ACTIVATE_PACKAGE_NOT_FOUND:             "Please Select Your Package",
	ERROR_IN_UPDATE_BANK_PROCESS:                    "Error Occur In Update Bank Info Process",
	ERROR_IN_PAYMENT_PROCESS:                        "Error Occur In Payment Process",
	ERROR_IN_GET_BONUS:                              "Error Occur In Get Bonus",
	ERROR_IN_GET_PENDING_PLACEMENT:                  "Error Occur In Get Pending Placement",
	ERROR_IN_GET_SPONSOR:                            "Error Occur In Get Sponsor",
	ERROR_IN_GET_MEMBERGUIDES:                       "Error Occur In Get Member Guides",
	ERROR_IN_GET_MEMBERANNOUNCEMENT:                 "Error Occur In Get Member Announcement",
	ERROR_IN_GET_DETAIL_MEMBERANNOUNCEMENT:          "Error Occur In Get Detail Member Announcement",
	ERROR_IN_TRANSFER_TO_YOURSELF:                   "Unable To Transfer To Yourself",
	ERROR_IN_TRANSFER_TO_INACTIVE_MEMBER:            "Cannot Transfer To Inactive Member",
	ERROR_IN_GET_PLACEMENT_TREE:                     "Error Occur In Get Placement Tree",
	ERROR_IN_GET_INFO_PLACEMENT_TREE:                "Error Occur In Get Info Placement Tree",
	ERROR_IN_GET_DETAIL_MEMBERGUIDES:                "Error Occur In Get Detail Member Guide",
	ERROR_IN_GET_ADMIN:                              "Error Occur In Get Admin",
	ERROR_IN_GET_USERGROUP:                          "Error Occur In Get Admin Group",
	ERROR_IN_CREATE_ADMIN_GROUP:                     "Error Occur In Create Admin Group",
	ERROR_IN_CREATE_ADMIN:                           "Error Occur In Create Admin",
	ERROR_IN_GET_SYSTEM_MENU:                        "Error Occur In Get System Menu",
	ERROR_IN_CREATE_SYSTEM_MENU:                     "Error Occur In Create System Menu",
	ERROR_IN_UPDATE_SYSTEM_MENU:                     "Error Occur In Update System Menu",
	ERROR_IN_GET_COUNTRIES:                          "Error Occur In Get Countries",
	ERROR_IN_CREATE_COUNTRY_PROCESS:                 "Error Occur In Create Country Process",
	ERROR_DUPLICATE_COUNTRY_CODE:                    "Country Code Already Taken",
	ERROR_IN_UPDATE_COUNTRY_PROCESS:                 "Error Occur In Update Country Process",
	ERROR_IN_UPDATE_ADMIN_GROUP:                     "Error Occur In Update Admin Group",
	ERROR_IN_GET_PAYMENT_SETTING:                    "Error Occur In Get Payment Setting",
	ERROR_IN_CREATE_PAYMENT_SETTING:                 "Error Occur In Create Payment Setting",
	ERROR_IN_UPDATE_PAYMENT_SETTING:                 "Error Occur In Update Payment Setting",
	ERROR_IN_GET_WALLET_TYPE:                        "Error Occur In Get Wallet Type",
	ERROR_IN_CREATE_WALLET_TYPE:                     "Error Occur In Create Wallet Type",
	ERROR_IN_UPDATE_WALLET_TYPE:                     "Error Occur In Update Wallet Type",
	ERROR_IN_GET_CONTACT_TYPE:                       "Error Occur In Get Contact Type",
	ERROR_IN_CREATE_CONTACT_TYPE:                    "Error Occur In Create Contact Type",
	ERROR_IN_UPDATE_CONTACT_TYPE:                    "Error Occur In Update Contact Type",
	ERROR_IN_GET_MEMBER_STATUS:                      "Error Occur In Get Member Status",
	ERROR_IN_CREATE_MEMBER_STATUS:                   "Error Occur In Create Member Status",
	ERROR_IN_UPDATE_MEMBER_STATUS:                   "Error Occur In Update Member Status",
	ERROR_IN_GET_MEMBER_TYPE:                        "Error Occur In Get Member Type",
	ERROR_IN_CREATE_MEMBER_TYPE:                     "Error Occur In Create Member Type",
	ERROR_IN_UPDATE_MEMBER_TYPE:                     "Error Occur In Update Member Type",
	ERROR_IN_CREATE_PAYMENT_TYPE:                    "Error Occur In Create Payment Type",
	ERROR_IN_UPDATE_PAYMENT_TYPE:                    "Error Occur In Update Payment Type",
	ERROR_IN_GET_ANNOUNCEMENT_LIST:                  "Error Occur In Get Announcement List",
	ERROR_IN_CREATE_ANNOUNCEMENT_LIST:               "Error Occur In Create Announcement List",
	ERROR_IN_UPDATE_ANNOUNCEMENT_LIST:               "Error Occur In Update Announcement List",
	ERROR_IN_GET_GENDER:                             "Error Occur In Get Gender",
	ERROR_IN_CREATE_GENDER:                          "Error Occur In Create Gender",
	ERROR_IN_UPDATE_GENDER:                          "Error Occur In Update Gender",
	ERROR_IN_GET_BANK:                               "Error Occur In Get Bank",
	ERROR_IN_CREATE_BANK:                            "Error Occur In Create Bank",
	ERROR_IN_UPDATE_BANK:                            "Error Occur In Update Bank",
	ERROR_IN_GET_RELATIONSHIP:                       "Error Occur In Get Relationship",
	ERROR_IN_CREATE_RELATIONSHIP:                    "Error Occur In Create Relationship",
	ERROR_IN_UPDATE_RELATIONSHIP:                    "Error Occur In Update Relationship",
	ERROR_IN_GET_CENTERTYPE:                         "Error Occur In Get Center Type",
	ERROR_IN_CREATE_CENTERTYPE:                      "Error Occur In Create Center Type",
	ERROR_IN_UPDATE_CENTERTYPE:                      "Error Occur In Update Center Type",
	ERROR_IN_GET_MARITAL_STATUS:                     "Error Occur In Get Marital Status",
	ERROR_IN_CREATE_MARITAL_STATUS:                  "Error Occur In Create Marital Status",
	ERROR_IN_UPDATE_MARITAL_STATUS:                  "Error Occur In Update Marital Status",
	ERROR_IN_GET_RACE:                               "Error Occur In Get Race",
	ERROR_IN_CREATE_RACE:                            "Error Occur In Create Race",
	ERROR_IN_UPDATE_RACE:                            "Error Occur In Update Race",
	ERROR_IN_GET_TERRITORY_TYPE:                     "Error Occur In Get Territory Type",
	ERROR_IN_CREATE_TERRITORY_TYPE:                  "Error Occur In Create Territory Type",
	ERROR_IN_UPDATE_TERRITORY_TYPE:                  "Error Occur In Update Territory Type",
	ERROR_IN_GET_TERRITORY:                          "Error Occur In Get Territory",
	ERROR_IN_CREATE_TERRITORY:                       "Error Occur In Create Territory",
	ERROR_IN_UPDATE_TERRITORY:                       "Error Occur In Update Territory",
	ERROR_IN_GET_WITHDRAW_PAYMENT_TYPE:              "Error Occur In Get Withdraw Payment Type",
	ERROR_IN_CREATE_WITHDRAW_PAYMENT_TYPE:           "Error Occur In Create Withdraw Payment Type",
	ERROR_IN_UPDATE_WITHDRAW_PAYMENT_TYPE:           "Error Occur In Update Withdraw Payment Type",
	ERROR_IN_GET_CURRENCY:                           "Error Occur In Get Currency",
	ERROR_IN_CREATE_CURRENCY:                        "Error Occur In Create Currency",
	ERROR_IN_UPDATE_CURRENCY:                        "Error Occur In Update Currency",
	ERROR_IN_GET_SYS_CURRENCY_RATE:                  "Error Occur In Get System Currency Rate",
	ERROR_IN_CREATE_SYS_CURRENCY_RATE:               "Error Occur In Create System Currency Rate",
	ERROR_IN_UPDATE_SYS_CURRENCY_RATE:               "Error Occur In Update System Currency Rate",
	ERROR_IN_GET_MODULE:                             "Error Occur In Get Module",
	ERROR_IN_CREATE_MODULE:                          "Error Occur In Create Module",
	ERROR_IN_UPDATE_MODULE:                          "Error Occur In Update Module",
	ERROR_IN_UPDATE_ADMIN_GROUP_PERMISSION:          "Error Occur In Update Admin Group Permission",
	ERROR_IN_DELETE_ADMIN_GROUP:                     "Error Occur In Delete Admin Group",
	ERROR_IN_GET_SALES_LIST:                         "Error Occur In Get Sales List",
	ERROR_IN_GET_PIN_LIST:                           "Error Occur In Get Pin List",
	ERROR_IN_GET_GROUP_TYPE:                         "Error Occur In Get Group Type",
	ERROR_IN_CANCEL_SALES:                           "Error Occur In Cancel Sales",
	ERROR_IN_CANCEL_PIN:                             "Error Occur In Cancel Pin",
	ERROR_IN_GET_GENEALOGY_UPLINE_TREE:              "Error Occur In Get Genealogy Upline Tree",
	ERROR_IN_GET_DOWNLOAD_LIST:                      "Error Occur In Get Download List",
	ERROR_IN_CREATE_DOWNLOAD_LIST:                   "Error Occur In Create Download List",
	ERROR_IN_UPDATE_DOWNLOAD_LIST:                   "Error Occur In Update Download List",
	ERROR_IN_GET_DOCUMENT_TYPE:                      "Error Occur In Get Document Type",
	ERROR_IN_CREATE_DOCUMENT_TYPE:                   "Error Occur In Create Document Type",
	ERROR_IN_UPDATE_DOCUMENT_TYPE:                   "Error Occur In Update Document Type",
	ERROR_IN_GET_DOC_TYPE:                           "Error Occur In Get Doc Type",
	ERROR_IN_GET_TABLE_NAME:                         "Error Occur In Get Table Name",
	ERROR_IN_GET_COMPANY:                            "Error Occur In Get Company",
	ERROR_IN_GET_CHANGE_LOT_LIST:                    "Error Occur In Get Change Lot List",
	ERROR_IN_CHANGE_SPONSOR:                         "Error Occur In Change Sponsor",
	ERROR_IN_CHANGE_UPLINE:                          "Error Occur In Change Upline",
	ERROR_IN_GET_UPLINE:                             "Error Occur In Get Upline",
	ERROR_IN_SUSPEND_MEMBER:                         "Error Occur In Suspend Member",
	ERROR_IN_REACTIVATE_MEMBER:                      "Error Occur In Reactivate Member",
	ERROR_IN_TERMINATE_MEMBER:                       "Error Occur In Terminate Member",
	ERROR_CAUSE_BY_MEMBER_STATUS_NOT_ACTIVE:         "Member Current Status Could Not Be Suspended",
	ERROR_CAUSE_BY_MEMBER_STATUS_NOT_SUSPEND:        "Member Current Status Could Not Be Reactivate",
	ERROR_CAUSE_BY_MEMBER_STATUS_ALREADY_TERMINATED: "This Member Is Already Terminated",
	ERROR_CAUSE_BY_MEMBER_STATUS_ALREADY_CANCELLED:  "This Member Is Already Cancelled",
	ERROR_IN_CREATE_AGENT:                           "Error Occur In Create Agent",
	ERROR_INVALID_MEMBER_SETTING_GROUP:              "Invalid Member Setting Group",
	ERROR_IN_GENERATE_DOCUMENT_NUMBER:               "Error Occur In Generate Document Number",
	ERROR_IN_GET_SUSPENDED_LIST:                     "Error Occur In Get Suspended List",
	ERROR_IN_GET_CANCELLED_LIST:                     "Error Occur In Get Cancelled List",
	ERROR_IN_GET_TERMINATED_LIST:                    "Error Occur In Get Terminated List",
	ERROR_IN_GET_MEMBER_STATUS_CHANGE_RECORD:        "Error Occur In Get Member Status Change Record",
	ERROR_IN_ADJUST_WALLET_PROCESS:                  "Error Occur In Adjust Wallet Process",
	ERROR_REQUIRED_PAYMENT_TYPE:                     "Payment Type Cannot Be Empty",
	ERROR_PAYMENT_TYPE_WRONG:                        "Invalid Payment Type",
	ERROR_IN_GET_TRANSACTION:                        "Error Occur In Get Transaction",
	ERROR_IN_GET_BALANCE:                            "Error Occur In Get Member Wallet Balance",
	ERROR_IN_GET_WALLET_SETTING:                     "Error Occur In Get Ewallet Setting",
	ERROR_IN_CREATE_WALLET_SETTING:                  "Error Occur In Create Ewallet Setting",
	ERROR_IN_UPDATE_WALLET_SETTING:                  "Error Occur In Update Ewallet Setting",
	ERROR_IN_UPDATE_MEMBER_WALLET_LOCK:              "Error Occur In Update Member Wallet Lock",
	ERROR_IN_GET_MEMBER_WALLET_LOCK:                 "Error Occur In Get Member Wallet Lock",
	ERROR_IN_GET_APPROVAL_LIST:                      "Error Occur In Get Approval List",
	ERROR_IN_GET_MEMBER_DETAIL:                      "Error Occur In Get Member Detail",
	ERROR_IN_CHECK_WALLET_TYPE:                      "Error Occur In Check Wallet Type",
	ERROR_IN_DELETE_ADMIN_GROUP_REMAIN_CHILD:        "Remaining Of Group Children, Can Not Delete Group",
	WALLET_MEMBER_ALREADY_HIDE:                      "Wallet Already Hidden, Setting No Changes",
	WALLET_MEMBER_ALREADY_UN_HIDE:                   "Wallet Already Available, Setting No Changes",
	ERROR_IN_SETTING_WALLET_MEMBER:                  "Error Occur In Setting Wallet Member Hide",
	ERROR_IN_GET_MEMBER_WALLET_HIDE:                 "Error Occur In Get Member Wallet Hide",
	ERROR_IN_LOCK_WALLET_MEMBER:                     "Error Occur In Lock Wallet Member",
	ERROR_IN_GET_CATEGORY:                           "Error Occur In Get Category",
	ERROR_IN_GET_PRODUCT:                            "Error Occur In Get Product",
	ERROR_IN_CREATE_PRODUCT:                         "Error Occur In Create Product",
	ERROR_IN_GET_TAX_TYPE:                           "Error Occur In Get Tax Type",
	ERROR_IN_GET_PRICE_TYPE:                         "Error Occur In Get Price Type",
	ERROR_IN_CREATE_PRICE_TYPE:                      "Error Occur In Create Price Type",
	ERROR_IN_UPDATE_PRICE_TYPE:                      "Error Occur In Update Price Type",
	ERROR_IN_GET_BRAND:                              "Error Occur In Get Brand",
	ERROR_IN_CREATE_PRICE_COUNTRY:                   "Error Occur In Create Price Country",
	ERROR_IN_UPDATE_PRICE_COUNTRY:                   "Error Occur In Update Price Country",
	ERROR_IN_UPDATE_PRODUCT:                         "Error Occur In Update Product",
	INVALID_ADJUSTMENT_AMOUNT:                       "Please Input Valid Adjustment Amount",
	INVALID_TRANSFER_AMOUNT:                         "Please Input Valid Transfer Amount",
	ERROR_IN_CREATE_ALBUM_PHOTO:                     "Error Occur In Create Photo",
	ERROR_IN_UPDATE_ALBUM_PHOTO:                     "Error Occur In Update Photo",
	ERROR_IN_DELETE_ALBUM_PHOTO:                     "Error Occur In Delete Photo",
	ERROR_IN_GET_ALBUM:                              "Error Occur In Get Photo",
	ERROR_IN_GET_ALBUM_VIDEO:                        "Error Occur In Get Video",
	ERROR_IN_CREATE_ALBUM_VIDEO:                     "Error Occur In Create Video",
	ERROR_IN_UPDATE_ALBUM_VIDEO:                     "Error Occur In Update Video",
	ERROR_IN_DELETE_ALBUM_VIDEO:                     "Error Occur In Delete Video",
	ERROR_IN_GET_ACTIVATION_CODE:                    "Error Occur In Get Activation Code",
	ERROR_IN_CREATE_SKU_CODE:                        "Error Occur In Create SKU Code",
	ERROR_IN_EDIT_SKU_CODE:                          "Error Occur In Edit SKU Code",
	ERROR_IN_DELETE_SKU_CODE:                        "Error Occur In Delete SKU Code",
	ERROR_IN_GET_SKU_CODE:                           "Error Occur In Get SKU Code",
	ERROR_DUPLICATE_SKU_CODE:                        "SKU Code Already Taken",
	ERROR_IN_GET_STORE:                              "Error Occur In Get Store View",
	ERROR_IN_GET_REGISTRATION_PACKAGE:               "Error Occur In Get Registration Package",
	ERROR_IN_CREATE_REGISTRATION_PACKAGE:            "Error Occur In Create Registration Package",
	ERROR_IN_GET_CUSTOMER_GROUP:                     "Error Occur In Get Customer Group",
	ERROR_IN_CREATE_CATEGORY:                        "Error Occur In Create Category",
	ERROR_IN_GET_ATTRIBUTE_SET:                      "Error Occur In Get Attribute Set",
	ERROR_INVALID_PARENT_CATEGORY:                   "Invalid Category Parent",
	ERROR_IN_GET_ATTRIBUTE:                          "Error Occur In Get Eav Attribute",
	ERROR_IN_GET_ATTRIBUTE_OPTION:                   "Error Occur In Get Eav Attribute Option",
	ERROR_IN_CREATE_PACKAGE:                         "Error Occur In Create Package",
	ERROR_IN_GET_SIMPLE_PRODUCT:                     "Error Occur In Get Simple Product",
	ERROR_IN_BINDING:                                "Error Occur In Bind",
	ERROR_IN_PIN_CODE_NOT_FOUND:                     "Pin Code Not Found",
	ERROR_IN_MAINTENANCE_PROCESS:                    "Error Occur In Maintenance Process",
	ERROR_IN_INVOICE_DETAIL:                         "Error Occur In Get Invoice Detail",
	ERROR_IN_GET_TOP_UP_REQUEST:                     "Error Occur In Get Top-up Request List",
	ERROR_IN_TOP_UP_REQUEST_ALREAY_PROCESS:          "Top-up Request Already Process",
	ERROR_IN_ACTIVATION_CODE:                        "Error Occur In Activate Code",
	ERROR_AUTH_FEATURE_PASSWORD:                     "Incorrect V-Office Password",
	ERROR_AUTH_IDENTITY_CODE:                        "Incorrect NRIC No",
	ERROR_IN_UPDATE_SYSTEM_SETTING:                  "Error Occur In Update System Static Setting",
	ERROR_IN_GET_SYSTEM_STATIC_SETTING:              "Error Occur In Get System Static Setting",
	INVALID_HASH:                                    "Invalid Hash",
	ERROR_IN_MATCH_ACTIVATE_CODE:                    "Invalid ECode",
	ERROR_IN_UPDATED_USED_ACTIVATE_CODE:             "Activate Code Already Used",
	ERROR_IN_GET_AVAILABLE_SLOT:                     "Error Occur In Get Available Slot",
	ERROR_PACKAGE_NOT_FOUND:                         "Error Occur In Get Package",
	ERROR_IN_QUERY_MEMBER:                           "Member Not Found",
	ERROR_IN_UPDATE_ATTRIBUTE_OPTION_VALUE:          "Error Occur In Update Option Value",
	ERROR_IN_CREATE_ATTRIBUTE_OPTION_VALUE:          "Error Occur In Create Option Value",
	ERROR_IN_UPDATE_BENEFICIARY:                     "Error Occur In Update Beneficiary Information",
	ERROR_IN_WITHDRAW_CHECK_GREATER_THAN_MIN:        "Withdraw Amount At Lease %.2f",
	ERROR_IN_CHECK_ACTIVATION_EXPIRY_DATE:           "E-Code activation duration was expired",
	ERROR_CHECK_PLACEMENT_TREE_NETWORK:              "Member Not Found",
	ERROR_IN_ASSIGN_MEMBER_RANK:                     "Error Occur In Assign Member Rank",
	ERROR_IN_ALREADY_ASSIGN_MEMBER_RANK:             "Member Already Assigned",
	ERROR_IN_UNDEFINED_MEMBER_RANK:                  "Member And Rank Undefined",
	ERROR_IN_GET_TIMEZONE:                           "Could Not Load",
	ERROR_IN_GET_TRANSFER_MEMBER:                    "Member Not Found!",
	ERROR_IN_MEMBER_NOT_EXISTS:                      "Member Not Found!",
	ERROR_IN_UPDATE_LOCKED_ECODE:                    "Could Not Update Locked ECode.",
	ERROR_IN_GET_INVOICE:                            "Error Occur In Get Invoice",
	ERROR_IN_CHECK_INVENTORY:                        "Product was Out Of Stock.",
	ERROR_IN_CHECK_PRODUCT_BUY_QUANTITY:             "Please Enter Suitable Product Quantity",
	ERROR_IN_GET_DEFAULT_STOCK:                      "Error Occur In Get Default Stock",
	ERROR_IN_PRODUCT_INVENTORY_NEGATIVE:             "Product Inventory can not be Negative",
	ERROR_IN_CANCEL_REGISTER:                        "Can Not Reverse Member Registration,",
	ERROR_IN_NO_CANCELLATION_ABILITY:                "Invoice Has No Cancellation Ability.",
	ERROR_IN_INVOICE_ALREADY_CANCELED:               "Invoice Already Canceled.",
	ERROR_IN_BONUS_RECALCULATION_ABILITY:            "Bonus Has No Recalculation Ability",
	ERROR_IN_CREAT_EVENT:                            "Error Occur In Create Event.",
	ERROR_IN_CHECK_TRAINING_KEY_NOT_FOUND:           "Training Key Not Found.",
	ERROR_IN_CHECK_TRAINING_KEY_USED:                "Training Key Used.",
	ERROR_IN_CHECK_EVENT_NOT_FOUND:                  "Event Not Found.",
	ERROR_IN_CHECK_EVENT_TICKET:                     "",
	ERROR_IN_CHECK_EVENT_TICKET_ALREADY_JOIN:        "",
	ERROR_IN_CHECK_TICKET_NOT_FOUND:                 "Ticket Not Found.",
	ERROR_IN_CHECK_REFRESHER_NOT_FOUND:              "Member Not Found.",
	ERROR_IN_WITHDRAW_CHECK_KEEP_WALLET_AMOUNT:      "Withdraw amount was too much. V-Token (redeemable) should remain at least RM%.2f.",
	ERROR_IN_DELETE_ANNOUNCEMENT:                    "Error Occur In Delete Announcement",
	ERROR_IN_UPDATE_LOCKED_ECODE_OF_INACTIVE_MEMBER: "Could not Update Expired ECode of Inactive Member",
	ERROR_IN_WITHDRAW_PROCESS:                       "Error Occur In Wallet Withdraw Process",
	ERROR_IN_CREAT_DISCOUNT_CODE:                    "Error Occur In Create Discount Code.",
	ERROR_IN_UPDATE_DISCOUNT_CODE:                   "Error Occur In Update Discount Code.",
	ERROR_DUPLICATE_DISCOUNT_CODE:                   "Discount Code already in use.",
	ERROR_DUPLICATE_IDENTITY:                        "Identity Number already in use.",
	ERROR_IN_CREATE_DOCUMENT:                        "Error Occur In Create Document.",
	ERROR_IN_DELETE_EVENT:                           "Error Occur In delete Event.",
	ERROR_PERIOD_DATE:                               "Invalid Period Of Time.",
	ERROR_IN_GET_STOCK:                              "Error Occur In Get Stock.",
	ERROR_IN_GET_TEAM_MEMBER:                        "Error Occur In Get Team Member.",
	ERROR_IN_GET_SLIDER:                             "Error Occur In Get Slider.",
	ERROR_IN_GET_POTENTIAL_MEMBER:                   "Error Occur In Get Potential Customer.",
	ERROR_IN_GET_INTRO_VIDEO:                        "Error Occur In Get Intro Video.",
	ERROR_IN_CHECK_INVALID_UPLINE:                   "Invalid Up-line",
	ERROR_IN_CHECK_SLOT:                             "Invalid Slot!",
	ERROR_IN_DELETE_SELF:                            "Can NOT Delete your Self!",
	ERROR_IN_DELETE_ROOT:                            "Can NOT Delete Root user!",
	ERROR_IN_INVALID_SPONSOR_CODE:                   "Invalid Sponsor Code",
	ERROR_IN_GET_SUPPLIER:                           "Error Occur In Get Supplier",
	ERROR_IN_DELETE_SUPPLIER:                        "Error Occur In Delete Supplier",
	ERROR_IN_UPDATE_SUPPLIER:                        "Error Occur In Update Supplier",
	ERROR_IN_CHANGE_UPLINE_VALIDATE_SELF_SLOT:       "Can Not Assign Member to it's Slot",
	ERROR_IN_CREATE_GOOD_RECEIVE:                    "Error Occur In Create Good Receive",
	ERROR_IN_GET_GOOD_RECEIVE:                       "Error Occur In Get Good Receive",
	ERROR_IN_GET_ADJUSTMENT:                         "Error Occur In Get Adjustment",
	ERROR_IN_CREATE_ADJUSTMENT:                      "Error Occur in Create Adjustment",
	ERROR_IN_CHANGE_UPLINE_VALIDATE_DOWNLINE_SLOT:   "Can Not Assign Member to it's Down Line Placement Tree",
	ERROR_IN_INVALID_TYPE:                           "Invalid Type",
	ERROR_IN_INVALID_SITE:                           "Invalid Site",
	ERROR_IN_INVALID_ACTION:                         "Invalid Action",
	ERROR_IN_UPDATE_WALLET_TRANSACTION:              "Error Occur In Update Wallet Transaction",
	ERROR_IN_GET_WALLET_TRANSACTION:                 "Error Occur In Get Wallet Transaction",
	ERROR_IN_CREATE_DELIVERY_SETTING:                "Error Occur In Create Delivery Setting ",
	ERROR_IN_EDIT_DELIVERY_SETTING:                  "Error Occur In Edit Delivery Setting ",
	ERROR_IN_GET_DELIVERY_SETTING:                   "Error Occur In Get Delivery Setting ",
	ERROR_IN_ACTIVE_RANGE_DESCOUNT_CODE:             "Invalid Date Range",
	ERROR_IN_ACTIVE_RANGE_DELIVERY_SETTING:          "Invalid Date Range",
	ERROR_IN_CHECK_DELIVERY_FEE_RANGE:               "Invalid Delivery Fee Range",
	ERROR_IN_GET_COMMISSION_SETTING:                 "Error Occur In Get Commission Setting",
	ERROR_IN_CREAT_BONUS_SETTING:                    "Error Occur In Create Bonus Setting",
	ERROR_IN_GET_BONUS_SETTING_DETAIL:               "Error Occur In Get Bonus Setting Detail",
	ERROR_IN_UPDATE_BONUS_SETTING:                   "Error Occur In Update Bonus Setting",
	ERROR_IN_CHECK_SLOT_IS_BUSY:                     "Slot Is Busy, Can't Assign New Member Yet, Please Choose Another Slot",
	ERROR_GET_LANGUAGES:                             "Error in getting Languages",
	ERROR_IN_CHECK_TRANSFER_WALLET_BALLANCE:         "Wallet Balance Not have Enough Money to Transfer",
	ERROR_IN_DELETE_ADMIN_UEER:                      "Error Occur In Delete Admin User",

	MEM_STATUS_TRACK_MESSAGE_NEW:                              "[AUTO]New member joined.",
	MEM_STATUS_TRACK_MESSAGE_E_CODE_OVER:                      "[AUTO]ECode Activation Duration expired.",
	MEM_STATUS_TRACK_MESSAGE_LAST_MAINTENANCE_OVER_2YEARS:     "[AUTO]Last maintenance was over 2 years.",
	MEM_STATUS_TRACK_MESSAGE_MAINTENANCE_EXPIRED:              "[AUTO]Maintenance expiry date over.",
	MEM_STATUS_TRACK_MESSAGE_MEMBERSHIP_OVER:                  "[AUTO]Membership expiry date over.",
	MEM_STATUS_TRACK_MESSAGE_ADMIN_MANUALLY:                   "[MANUAL]Admin manually change member status(Active/Inactive).",
	MEM_STATUS_TRACK_MESSAGE_ADMIN_UPD_MEMBERSHIP:             "[AUTO]Affected by changing manually Membership Expiry Date of Admin.",
	MEM_STATUS_TRACK_MESSAGE_ADMIN_UPD_MAINTENANCE:            "[AUTO]Affected by changing manually Maintenance Expiry Date of Admin.",
	MEM_STATUS_TRACK_MESSAGE_ADMIN_UPD_UPGRADE:                "[AUTO]Affected by changing manually Upgrade Expiry Date of Admin.",
	MEM_STATUS_TRACK_MESSAGE_MEMBER_PACKAGE_PURCHASE_COMEBACK: "[AUTO]Affected by member Package Purchase comeback.",
	MEM_STATUS_TRACK_MESSAGE_MEMBER_REGISTER_COMEBACK:         "[AUTO]Affected by member Register comeback.",
	MEM_STATUS_TRACK_MESSAGE_MEMBER_MAINTENANCE_COMEBACK:      "[AUTO]Affected by member Maintenance comeback.",
	MEM_STATUS_TRACK_MESSAGE_MEMBER_UPGRADE_COMEBACK:          "[AUTO]Affected by member Upgrade comeback.",

	MEM_PACKAGE_TRACK_MESSAGE_NEW:              "[MANUAL]New member joined.",
	MEM_PACKAGE_TRACK_MESSAGE_MANUALLY_UPGRADE: "[MANUAL]Member Upgrade.",
	MEM_PACKAGE_TRACK_MESSAGE_ADMIN_REVERT:     "[MANUAL]Admin Revert Upgradation.",

	EXPIRED_DATE_TRACK_MESSAGE_BY_PURCHASE:    "[AUTO]Expiry date been extended due to Package Purchasing.",
	EXPIRED_DATE_TRACK_MESSAGE_BY_REGISTER:    "[AUTO]Expiry date initially set.",
	EXPIRED_DATE_TRACK_MESSAGE_BY_MAINTENANCE: "[AUTO]Expiry date been extended due to Maintenance.",
	EXPIRED_DATE_TRACK_MESSAGE_BY_UPGRADE:     "[AUTO]Expiry date been extended due to Upgradation.",
	EXPIRED_DATE_TRACK_MESSAGE_BY_ADMIN:       "[MANUAL]Admin manually change Expired Date.",
	EXPIRED_DATE_TRACK_MESSAGE_BY_REVERT:      "[AUTO]Expiry date been reverted due to Sale Cancellation.",
}
