// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/chi07/todo/internal/model"

	uuid "github.com/google/uuid"
)

// CreateTaskService is an autogenerated mock type for the CreateTaskService type
type CreateTaskService struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, t
func (_m *CreateTaskService) CreateTask(ctx context.Context, t *model.Task) (uuid.UUID, error) {
	ret := _m.Called(ctx, t)

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func(context.Context, *model.Task) uuid.UUID); ok {
		r0 = rf(ctx, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.Task) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
