// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldTaskLimit holds the string denoting the task_limit field in the database.
	FieldTaskLimit = "task_limit"
	// EdgeUserTask holds the string denoting the user_task edge name in mutations.
	EdgeUserTask = "user_task"
	// Table holds the table name of the user in the database.
	Table = "users"
	// UserTaskTable is the table that holds the user_task relation/edge.
	UserTaskTable = "tasks"
	// UserTaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	UserTaskInverseTable = "tasks"
	// UserTaskColumn is the table column denoting the user_task relation/edge.
	UserTaskColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
	FieldTaskLimit,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTaskLimit holds the default value on creation for the "task_limit" field.
	DefaultTaskLimit int
)
