language: node_js
node_js:
  - '12'
services:
  - postgresql
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=6363
    - SQL_URL=postgres://postgres:123456@localhost:5432/postgres
    - JWT_SECRET=xxxxxx
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
