###
### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "username": "daiphuc",
  "password": "password"
}

###
### Create task
POST http://localhost:8080/api/v1/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoiZGFpcGh1YyIsImV4cCI6MTY0MzE2Nzk1Mn0.t5YQx5u5HapEnzFwQWfNwd8W40mC5l9ffKoBsNmb6o8

{
  "name": "Task 1",
  "content": "To do task 1"
}