version: '3.5'
services:
  rabbitmq:
    build: ./other-services/rabbitmq
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - simple_app_net
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "15672"
      - "5672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

  mongodb:
    build: ./other-services/mongodb
    restart: always
    networks:
      - simple_app_net
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - "mongodb-data:/data/db"
  todo_svc:
    image: sp-todo_svc
    build:
      context: ./apps/todo_svc
      dockerfile: Dockerfile.local
    restart: always
    networks:
      - simple_app_net
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "3000:3000"
      - "7000:9229"
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_USER
      - MONGO_PASS
      - RABBITMQ_HOST
      - RABBITMQ_PROTOCOL
      - RABBITMQ_USER
      - RABBITMQ_PASS
    volumes:
      - "./apps/todo_svc:/home/node/app"
      - /home/node/app/node_modules

networks:
  simple_app_net:
    driver: bridge
volumes:
  rabbitmq-data:
    driver: local
  mongodb-data:
    driver: local
