# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  db-postgresql:
    container_name: postgres13
    image: postgres:13.1
    volumes:
      - ../storage/postgresql:/var/run/postgresql
      # - /var/run/postgresql:/var/run/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - system
 
networks:
  system:
    driver: bridge
