version: "3.7"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - pg_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "${PGADMIN_LISTEN_PORT}:80"
    volumes:
      - pg_admin_data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - pg_net

networks:
  pg_net:
    driver: bridge

volumes:
  pg_data:
  pg_admin_data:
