version: "3"
services:
  # web:
  #   container_name: todo_web
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 9090:9090
  
  db:
    image: mysql/mysql-server:8.0
    container_name: todo_db
    command: ["mysqld", "--authentication_policy=mysql_native_password"]
    environment:
      MYSQL_DATABASE: "todo"
      MYSQL_USER: "triet_truong"
      MYSQL_PASSWORD: "pw"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
      container_name: todo_redis
      image: "redis:alpine"
      ports:
        - 6379:6379



