#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DB_USER LOGIN PASSWORD '$DB_PASSWORD';
  CREATE DATABASE $DB_NAME;
  CREATE DATABASE ${DB_NAME}_test;
  GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME}_test TO $DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_NAME" <<-EOSQL
  CREATE EXTENSION pgcrypto;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$DB_NAME"_test <<-EOSQL
  CREATE EXTENSION pgcrypto;
EOSQL