// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Task struct {
	ID        int32     `json:"id"`
	Title     string    `json:"title"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID               int32     `json:"id"`
	UserName         string    `json:"user_name"`
	HashedPassword   string    `json:"hashed_password"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	MaximumTaskInDay int32     `json:"maximum_task_in_day"`
}
