// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"net/http"
	"togo/domain/handler"
	"togo/domain/middlewares"
	"togo/domain/repositories"
	"togo/domain/services"
)

// Injectors from wire.go:

func InitHTTPServer(ctx context.Context) (http.Handler, error) {
	middleware := middlewares.NewMiddleware()
	todoRepository := repositories.NewTodoRepository()
	todoService := services.NewTodoService(todoRepository)
	httpHandler := handler.NewHTTPServer(middleware, todoService)
	return httpHandler, nil
}
