// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package togo_public_api_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TogoPublicAPIServiceClient is the client API for TogoPublicAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TogoPublicAPIServiceClient interface {
	ListTask(ctx context.Context, in *ListTaskRequest, opts ...grpc.CallOption) (*ListTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	RegisterOrLogin(ctx context.Context, in *RegisterOrLoginRequest, opts ...grpc.CallOption) (*RegisterOrLoginResponse, error)
}

type togoPublicAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTogoPublicAPIServiceClient(cc grpc.ClientConnInterface) TogoPublicAPIServiceClient {
	return &togoPublicAPIServiceClient{cc}
}

func (c *togoPublicAPIServiceClient) ListTask(ctx context.Context, in *ListTaskRequest, opts ...grpc.CallOption) (*ListTaskResponse, error) {
	out := new(ListTaskResponse)
	err := c.cc.Invoke(ctx, "/togo.public_api.v1.TogoPublicAPIService/ListTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *togoPublicAPIServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/togo.public_api.v1.TogoPublicAPIService/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *togoPublicAPIServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/togo.public_api.v1.TogoPublicAPIService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *togoPublicAPIServiceClient) RegisterOrLogin(ctx context.Context, in *RegisterOrLoginRequest, opts ...grpc.CallOption) (*RegisterOrLoginResponse, error) {
	out := new(RegisterOrLoginResponse)
	err := c.cc.Invoke(ctx, "/togo.public_api.v1.TogoPublicAPIService/RegisterOrLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TogoPublicAPIServiceServer is the server API for TogoPublicAPIService service.
// All implementations should embed UnimplementedTogoPublicAPIServiceServer
// for forward compatibility
type TogoPublicAPIServiceServer interface {
	ListTask(context.Context, *ListTaskRequest) (*ListTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	RegisterOrLogin(context.Context, *RegisterOrLoginRequest) (*RegisterOrLoginResponse, error)
}

// UnimplementedTogoPublicAPIServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTogoPublicAPIServiceServer struct {
}

func (UnimplementedTogoPublicAPIServiceServer) ListTask(context.Context, *ListTaskRequest) (*ListTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTask not implemented")
}
func (UnimplementedTogoPublicAPIServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTogoPublicAPIServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTogoPublicAPIServiceServer) RegisterOrLogin(context.Context, *RegisterOrLoginRequest) (*RegisterOrLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterOrLogin not implemented")
}

// UnsafeTogoPublicAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TogoPublicAPIServiceServer will
// result in compilation errors.
type UnsafeTogoPublicAPIServiceServer interface {
	mustEmbedUnimplementedTogoPublicAPIServiceServer()
}

func RegisterTogoPublicAPIServiceServer(s grpc.ServiceRegistrar, srv TogoPublicAPIServiceServer) {
	s.RegisterService(&TogoPublicAPIService_ServiceDesc, srv)
}

func _TogoPublicAPIService_ListTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TogoPublicAPIServiceServer).ListTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/togo.public_api.v1.TogoPublicAPIService/ListTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TogoPublicAPIServiceServer).ListTask(ctx, req.(*ListTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TogoPublicAPIService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TogoPublicAPIServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/togo.public_api.v1.TogoPublicAPIService/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TogoPublicAPIServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TogoPublicAPIService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TogoPublicAPIServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/togo.public_api.v1.TogoPublicAPIService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TogoPublicAPIServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TogoPublicAPIService_RegisterOrLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterOrLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TogoPublicAPIServiceServer).RegisterOrLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/togo.public_api.v1.TogoPublicAPIService/RegisterOrLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TogoPublicAPIServiceServer).RegisterOrLogin(ctx, req.(*RegisterOrLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TogoPublicAPIService_ServiceDesc is the grpc.ServiceDesc for TogoPublicAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TogoPublicAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "togo.public_api.v1.TogoPublicAPIService",
	HandlerType: (*TogoPublicAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTask",
			Handler:    _TogoPublicAPIService_ListTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TogoPublicAPIService_GetTask_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _TogoPublicAPIService_CreateTask_Handler,
		},
		{
			MethodName: "RegisterOrLogin",
			Handler:    _TogoPublicAPIService_RegisterOrLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/togo_public_api.proto",
}
