CREATE TABLE IF NOT EXISTS users (
	id SERIAL NOT NULL,
    username TEXT NOT NULL,
	password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    CONSTRAINT username_uq UNIQUE (username),
	CONSTRAINT users_pk PRIMARY KEY (id)
);