// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/manabie-com/togo/internal/storages/ent/schema"
	"github.com/manabie-com/togo/internal/storages/ent/task"
	"github.com/manabie-com/togo/internal/storages/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTaskID is the schema descriptor for task_id field.
	taskDescTaskID := taskFields[0].Descriptor()
	// task.TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	task.TaskIDValidator = taskDescTaskID.Validators[0].(func(string) error)
	// taskDescContent is the schema descriptor for content field.
	taskDescContent := taskFields[1].Descriptor()
	// task.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	task.ContentValidator = taskDescContent.Validators[0].(func(string) error)
	// taskDescCreatedDate is the schema descriptor for created_date field.
	taskDescCreatedDate := taskFields[2].Descriptor()
	// task.DefaultCreatedDate holds the default value on creation for the created_date field.
	task.DefaultCreatedDate = taskDescCreatedDate.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserID is the schema descriptor for user_id field.
	userDescUserID := userFields[0].Descriptor()
	// user.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	user.UserIDValidator = userDescUserID.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescMaxTodo is the schema descriptor for max_todo field.
	userDescMaxTodo := userFields[3].Descriptor()
	// user.DefaultMaxTodo holds the default value on creation for the max_todo field.
	user.DefaultMaxTodo = userDescMaxTodo.Default.(int)
}
