// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Task struct {
	ID         int32     `json:"id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	IsComplete bool      `json:"is_complete"`
	UserID     int64     `json:"user_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID        int32     `json:"id"`
	FullName  string    `json:"full_name"`
	Maximum   int32     `json:"maximum"`
	CreatedAt time.Time `json:"created_at"`
}
