// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"
)

const countTasks = `-- name: CountTasks :one
SELECT count(*) FROM tasks WHERE user_id = $1
`

func (q *Queries) CountTasks(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, content, is_complete, user_id) VALUES ($1, $2, $3, $4) RETURNING id, title, content, is_complete, user_id, created_at
`

type CreateTaskParams struct {
	Title      string `json:"title"`
	Content    string `json:"content"`
	IsComplete bool   `json:"is_complete"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Content,
		arg.IsComplete,
		arg.UserID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.IsComplete,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, maximum) VALUES ($1, $2) RETURNING id, full_name, maximum, created_at
`

type CreateUserParams struct {
	FullName string `json:"full_name"`
	Maximum  int32  `json:"maximum"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FullName, arg.Maximum)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Maximum,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, full_name, maximum, created_at FROM users WHERE full_name = $1 LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, fullName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, fullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Maximum,
		&i.CreatedAt,
	)
	return i, err
}
