// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock_togo_internal_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	sync "sync"
	"togo-public-api/internal/service/togo_internal_v1"
)

// Ensure, that TogoInternalServiceClientMock does implement togo_internal_v1.TogoInternalServiceClient.
// If this is not the case, regenerate this file with moq.
var _ togo_internal_v1.TogoInternalServiceClient = &TogoInternalServiceClientMock{}

// TogoInternalServiceClientMock is a mock implementation of togo_internal_v1.TogoInternalServiceClient.
//
// 	func TestSomethingThatUsesTogoInternalServiceClient(t *testing.T) {
//
// 		// make and configure a mocked togo_internal_v1.TogoInternalServiceClient
// 		mockedTogoInternalServiceClient := &TogoInternalServiceClientMock{
// 			CreateTaskFunc: func(ctx context.Context, in *togo_internal_v1.CreateTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.Task, error) {
// 				panic("mock out the CreateTask method")
// 			},
// 			GetTaskFunc: func(ctx context.Context, in *togo_internal_v1.GetTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.Task, error) {
// 				panic("mock out the GetTask method")
// 			},
// 			ListTaskFunc: func(ctx context.Context, in *togo_internal_v1.ListTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.ListTaskResponse, error) {
// 				panic("mock out the ListTask method")
// 			},
// 		}
//
// 		// use mockedTogoInternalServiceClient in code that requires togo_internal_v1.TogoInternalServiceClient
// 		// and then make assertions.
//
// 	}
type TogoInternalServiceClientMock struct {
	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(ctx context.Context, in *togo_internal_v1.CreateTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.Task, error)

	// GetTaskFunc mocks the GetTask method.
	GetTaskFunc func(ctx context.Context, in *togo_internal_v1.GetTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.Task, error)

	// ListTaskFunc mocks the ListTask method.
	ListTaskFunc func(ctx context.Context, in *togo_internal_v1.ListTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.ListTaskResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *togo_internal_v1.CreateTaskRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// GetTask holds details about calls to the GetTask method.
		GetTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *togo_internal_v1.GetTaskRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// ListTask holds details about calls to the ListTask method.
		ListTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *togo_internal_v1.ListTaskRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockCreateTask sync.RWMutex
	lockGetTask    sync.RWMutex
	lockListTask   sync.RWMutex
}

// CreateTask calls CreateTaskFunc.
func (mock *TogoInternalServiceClientMock) CreateTask(ctx context.Context, in *togo_internal_v1.CreateTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.Task, error) {
	callInfo := struct {
		Ctx  context.Context
		In   *togo_internal_v1.CreateTaskRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	mock.lockCreateTask.Unlock()
	if mock.CreateTaskFunc == nil {
		var (
			taskOut *togo_internal_v1.Task
			errOut  error
		)
		return taskOut, errOut
	}
	return mock.CreateTaskFunc(ctx, in, opts...)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//     len(mockedTogoInternalServiceClient.CreateTaskCalls())
func (mock *TogoInternalServiceClientMock) CreateTaskCalls() []struct {
	Ctx  context.Context
	In   *togo_internal_v1.CreateTaskRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *togo_internal_v1.CreateTaskRequest
		Opts []grpc.CallOption
	}
	mock.lockCreateTask.RLock()
	calls = mock.calls.CreateTask
	mock.lockCreateTask.RUnlock()
	return calls
}

// GetTask calls GetTaskFunc.
func (mock *TogoInternalServiceClientMock) GetTask(ctx context.Context, in *togo_internal_v1.GetTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.Task, error) {
	callInfo := struct {
		Ctx  context.Context
		In   *togo_internal_v1.GetTaskRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockGetTask.Lock()
	mock.calls.GetTask = append(mock.calls.GetTask, callInfo)
	mock.lockGetTask.Unlock()
	if mock.GetTaskFunc == nil {
		var (
			taskOut *togo_internal_v1.Task
			errOut  error
		)
		return taskOut, errOut
	}
	return mock.GetTaskFunc(ctx, in, opts...)
}

// GetTaskCalls gets all the calls that were made to GetTask.
// Check the length with:
//     len(mockedTogoInternalServiceClient.GetTaskCalls())
func (mock *TogoInternalServiceClientMock) GetTaskCalls() []struct {
	Ctx  context.Context
	In   *togo_internal_v1.GetTaskRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *togo_internal_v1.GetTaskRequest
		Opts []grpc.CallOption
	}
	mock.lockGetTask.RLock()
	calls = mock.calls.GetTask
	mock.lockGetTask.RUnlock()
	return calls
}

// ListTask calls ListTaskFunc.
func (mock *TogoInternalServiceClientMock) ListTask(ctx context.Context, in *togo_internal_v1.ListTaskRequest, opts ...grpc.CallOption) (*togo_internal_v1.ListTaskResponse, error) {
	callInfo := struct {
		Ctx  context.Context
		In   *togo_internal_v1.ListTaskRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockListTask.Lock()
	mock.calls.ListTask = append(mock.calls.ListTask, callInfo)
	mock.lockListTask.Unlock()
	if mock.ListTaskFunc == nil {
		var (
			listTaskResponseOut *togo_internal_v1.ListTaskResponse
			errOut              error
		)
		return listTaskResponseOut, errOut
	}
	return mock.ListTaskFunc(ctx, in, opts...)
}

// ListTaskCalls gets all the calls that were made to ListTask.
// Check the length with:
//     len(mockedTogoInternalServiceClient.ListTaskCalls())
func (mock *TogoInternalServiceClientMock) ListTaskCalls() []struct {
	Ctx  context.Context
	In   *togo_internal_v1.ListTaskRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *togo_internal_v1.ListTaskRequest
		Opts []grpc.CallOption
	}
	mock.lockListTask.RLock()
	calls = mock.calls.ListTask
	mock.lockListTask.RUnlock()
	return calls
}
