# Generated by Django 3.2.5 on 2022-06-22 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='auth.user'),
            preserve_default=False,
        ),
    ]
