// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	storages "github.com/manabie-com/togo/internal/storages"
)

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: ctx, t
func (_m *DB) AddTask(ctx context.Context, t *storages.Task) error {
	ret := _m.Called(ctx, t)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storages.Task) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountTasks provides a mock function with given fields: ctx, userID, createdDate
func (_m *DB) CountTasks(ctx context.Context, userID string, createdDate string) (sql.NullInt32, error) {
	ret := _m.Called(ctx, userID, createdDate)

	var r0 sql.NullInt32
	if rf, ok := ret.Get(0).(func(context.Context, string, string) sql.NullInt32); ok {
		r0 = rf(ctx, userID, createdDate)
	} else {
		r0 = ret.Get(0).(sql.NullInt32)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, createdDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveTasks provides a mock function with given fields: ctx, userID, createdDate
func (_m *DB) RetrieveTasks(ctx context.Context, userID sql.NullString, createdDate sql.NullString) ([]*storages.Task, error) {
	ret := _m.Called(ctx, userID, createdDate)

	var r0 []*storages.Task
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullString, sql.NullString) []*storages.Task); ok {
		r0 = rf(ctx, userID, createdDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storages.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, sql.NullString, sql.NullString) error); ok {
		r1 = rf(ctx, userID, createdDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveUser provides a mock function with given fields: ctx, userID
func (_m *DB) RetrieveUser(ctx context.Context, userID string) (*storages.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *storages.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *storages.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storages.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateUser provides a mock function with given fields: ctx, userID, pwd
func (_m *DB) ValidateUser(ctx context.Context, userID sql.NullString, pwd sql.NullString) bool {
	ret := _m.Called(ctx, userID, pwd)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, sql.NullString, sql.NullString) bool); ok {
		r0 = rf(ctx, userID, pwd)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
