// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package postgres

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  password
) VALUES (
  $1
)
RETURNING id, password, max_todo
`

func (q *Queries) CreateUser(ctx context.Context, password string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, password)
	var i User
	err := row.Scan(&i.ID, &i.Password, &i.MaxTodo)
	return i, err
}
