package errorx

var (
	// ErrInternal ...
	ErrInternal = Error("1", 500, "internal_server_error", "Lỗi từ hệ thống internal")
	// ErrDatabase ...
	ErrDatabase = Error("2", 500, "database_error", "Lỗi từ cơ sở dữ liệu database")
	// ErrInvalidParameter ...
	ErrInvalidParameter = Error("3", 400, "invalid_parameter", "Parameter không hợp lệ")
	// ErrAuthFailure ...
	ErrAuthFailure = Error("4", 401, "auth_failure", "Xác thực thất bại")
	// ErrAuthority ...
	ErrForbidden = Error("5", 403, "authority_error", "Không thể truy cập đến tài nguyên")
	// ErrInvalidRefreshToken ...
	ErrInvalidRefreshToken = Error("6", 401, "invalid_refresh_token", "Refresh token không hợp lệ")
	// ErrRefreshTokenExpired ...
	ErrRefreshTokenExpired = Error("7", 401, "refresh_token_expired", "Refresh token hết hạn")
	// ErrInvalidRefreshToken ...
	ErrInvalidAccessToken = Error("8", 401, "invalid_access_token", "Access token không hợp lệ")
	// ErrRefreshTokenExpired ...
	ErrAccessTokenExpired = Error("9", 401, "access_token_expired", "Access token hết hạn")
)
