@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> TodoApp: POST /tasks

group successful case
User <-- TodoApp: 201 Created
end

group failed validation case
User <-- TodoApp: 400 Bad Request
end

group other failure case
User <-- TodoApp: 500 Internal Server Error

@enduml