exports.CODE_SUCCESS = 200 # OK
exports.CODE_BAD_REQUEST = 400 # Bad Request
exports.CODE_UNAUTHORIZED = 401 # Unauthorized
exports.CODE_FORBIDDEN = 403 # Forbidden
exports.CODE_PAYMENT_REQUIRED = 402 # Payment Required
exports.CODE_NOT_FOUND = 404 # Not Found
exports.CODE_MISS_PARAMETER = 406 # Not Acceptable
exports.CODE_ERROR = 500 # Internal Server Error
exports.CODE_UNSUPPORTED_API = 501 # Not Implemented