// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/triet-truong/todo/todo/model"
)

// TodoRepository is an autogenerated mock type for the TodoRepository type
type TodoRepository struct {
	mock.Mock
}

// InsertItem provides a mock function with given fields: item
func (_m *TodoRepository) InsertItem(item model.TodoItemModel) error {
	ret := _m.Called(item)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TodoItemModel) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectUser provides a mock function with given fields: id
func (_m *TodoRepository) SelectUser(id uint) (model.UserModel, error) {
	ret := _m.Called(id)

	var r0 model.UserModel
	if rf, ok := ret.Get(0).(func(uint) model.UserModel); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.UserModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
