// Code generated by mockery 2.9.4. DO NOT EDIT.

package todo

import mock "github.com/stretchr/testify/mock"

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}
