// Code generated by sqlc. DO NOT EDIT.

package postgresql

import (
	"time"
)

type Task struct {
	ID          int32     `json:"id"`
	Content     string    `json:"content"`
	UserID      int32     `json:"user_id"`
	CreatedDate time.Time `json:"created_date"`
	IsDone      bool      `json:"is_done"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	MaxTodo   int32     `json:"max_todo"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
