// Code generated by sqlc. DO NOT EDIT.
// source: tasks.sql

package postgresql

import (
	"context"
)

const deleteTask = `-- name: DeleteTask :exec
DELETE
FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, content, user_id, created_date, is_done, created_at, updated_at
FROM tasks
WHERE id = $1
  AND user_id = $2
LIMIT 1
`

type GetTaskParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.CreatedDate,
		&i.IsDone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, content, user_id, created_date, is_done, created_at, updated_at
FROM tasks
WHERE user_id = $1
ORDER BY id
`

func (q *Queries) ListTasks(ctx context.Context, userID int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.UserID,
			&i.CreatedDate,
			&i.IsDone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET is_done = $2
WHERE id = $1
`

type UpdateTaskParams struct {
	ID     int32 `json:"id"`
	IsDone bool  `json:"is_done"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask, arg.ID, arg.IsDone)
	return err
}
