// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package postgresql

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, username, password, max_todo, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.MaxTodo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
