CREATE DATABASE togo

CREATE TABLE Account (
    Id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,
    Name varchar(256) NOT NULL,
    Email varchar(256),
    Username VARCHAR(256),
    Password VARCHAR(256) NOT NULL,
    Type VARCHAR(256),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

CREATE TABLE Todo (
    Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    AccountId INT UNSIGNED,
    Title varchar(256) NOT NULL,
    Description varchar(256),
    Status VARCHAR(256),
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (AccountId) REFERENCES Account(Id)
);