// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetTaskByID(ctx context.Context, id uint64) (TodoTask, error)
	GetTaskByUserID(ctx context.Context, userID uint64) ([]TodoTask, error)
	InsertTask(ctx context.Context, arg InsertTaskParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
