server:
  addr: ""
  port: "8080"
  shutdown_timeout: 10s
  read_header_timeout: 10s
  write_timeout: 10s
  read_timeout: 10s

env: "dev" # release

db:
  host: "localhost"
  port: 5432
  user: "username"
  password: "password"
  name: "togo"
  driver: "postgres"

log:
  level: "debug" # [debug, info,warn, error]
  encode: "console" # json or console
  file: "log.log"

token:
  secret_key: "Xhu091or5QiwwpxrAGxNaz09+AlVbi9t9HiJmBknsOA="
  duration: 60m