CREATE TABLE IF NOT EXISTS users (
	id VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	max_todo INTEGER DEFAULT 5 NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT users_PK PRIMARY KEY (id)
);

INSERT INTO users (id, password, max_todo) VALUES('firstUser', 'example', 5);

CREATE TABLE IF NOT EXISTS tasks (
	id VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT tasks_PK PRIMARY KEY (id),
	CONSTRAINT tasks_FK FOREIGN KEY (user_id) REFERENCES users(id)
);
