{
 "title": "Togo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(irate(process_cpu_seconds_total{job=~\"togo-.+\"}[$__rate_interval]) * 100) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{job=~\"togo-.*\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(go_goroutines{job=~\"togo-.*\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Product", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_started_total{job=~\"togo-.*\"}[$__interval])) by (grpc_method, grpc_service)",
     "legendFormat": "{{grpc_method}} ({{grpc_service}})"
    }
   ]
  },
  {
   "title": "Request latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{job=~\"togo-.*\"}[1m])) by (grpc_method, grpc_service, le)) ",
     "legendFormat": "{{grpc_method}} ({{grpc_service}})"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=~\"togo-.*\", grpc_code!=\"OK\"}[$__interval])) by (grpc_method, grpc_service, grpc_code)",
     "legendFormat": "{{grpc_method}} ({{grpc_service}}) {{grpc_code}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=~\"togo-.*\"}[$__rate_interval])) by (grpc_method, grpc_service)",
     "legendFormat": "{{grpc_method}} ({{grpc_service}})"
    }
   ]
  }
 ]
}