GET http://localhost:5050/login?user_id=firstUser&password=example
Accept: application/json


//Saving a variable
> {%
 client.global.set("auth_token", response.body.data);
%}

###
GET http://localhost:5050/tasks?created_date=2020-06-29
Accept: application/json
Authorization: {{auth_token}}
###

POST http://localhost:5050/tasks
Accept: application/json
Content-Type: application/json
Authorization: {{auth_token}}

{
  "content" : "another content"
}

###