server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: manabie
    password: Manabie@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
    show-sql: true
  profiles:
    active: prod
app:
  default-quote-task: 10
  jwt-secret-key: "5evwaFf/JMT6G4uAhHK8BZREcLQ="
  jwt-issuer: todo.manabie.spring
  jwt-expire-in-seconds: 86400
logging:
  level:
    com.manabie.todo: debug
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org.hibernate.type.descriptor.sql: trace