FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY ./Togo.sln ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ${file%.*}/ && mv $file ${file%.*}/; done
COPY . .

WORKDIR /src/Togo.Api.IntegrationTests
ENTRYPOINT ["dotnet", "test"]
