# Generated by Django 3.2.13 on 2022-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
