# Generated by Django 3.2.13 on 2022-05-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togoapi', '0003_usertask_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='togoapi.usertask'),
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='togoapi.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
