# Generated by Django 3.2.13 on 2022-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togoapi', '0006_auto_20220511_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='task_today',
            field=models.IntegerField(default=0),
        ),
    ]
