// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	storages "github.com/banhquocdanh/togo/internal/storages"
	mock "github.com/stretchr/testify/mock"
)

// StoreInterface is an autogenerated mock type for the StoreInterface type
type StoreInterface struct {
	mock.Mock
}

// AddTask provides a mock function with given fields: ctx, t
func (_m *StoreInterface) AddTask(ctx context.Context, t *storages.Task) error {
	ret := _m.Called(ctx, t)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storages.Task) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetrieveTasks provides a mock function with given fields: ctx, userID, createdDate
func (_m *StoreInterface) RetrieveTasks(ctx context.Context, userID string, createdDate string) ([]*storages.Task, error) {
	ret := _m.Called(ctx, userID, createdDate)

	var r0 []*storages.Task
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*storages.Task); ok {
		r0 = rf(ctx, userID, createdDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storages.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, createdDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateUser provides a mock function with given fields: ctx, userID, pwd
func (_m *StoreInterface) ValidateUser(ctx context.Context, userID string, pwd string) bool {
	ret := _m.Called(ctx, userID, pwd)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, pwd)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
